
// This file has been generated by the GUI designer. Do not modify.
namespace gtk
{
	public partial class ThirdWindow
	{
		private global::Gtk.Notebook notebook5;

		private global::Gtk.Table table2;

		private global::Gtk.Button IngresarProfesor;

		private global::Gtk.Label label37;

		private global::Gtk.Button RegistradoProfesor;

		private global::Gtk.VBox vbox23;

		private global::Gtk.Label Label28;

		private global::Gtk.Label label29;

		private global::Gtk.Label label31;

		private global::Gtk.VBox vbox25;

		private global::Gtk.Entry NombreProfesor;

		private global::Gtk.Entry ApellidoProfesor;

		private global::Gtk.Entry EdadProfesor;

		private global::Gtk.VBox vbox29;

		private global::Gtk.Label label33;

		private global::Gtk.Label label35;

		private global::Gtk.Label label39;

		private global::Gtk.VBox vbox31;

		private global::Gtk.Entry DescripcionProfesor;

		private global::Gtk.Entry EspecialidadProfesor;

		private global::Gtk.Entry RutProfesor;

		private global::Gtk.Button VolverProfesor;

		private global::Gtk.Label UsuarioProfesor;

		private global::Gtk.Table table5;

		private global::Gtk.Button IngresarAlumno;

		private global::Gtk.Button RegistradoAlumno;

		private global::Gtk.VBox vbox42;

		private global::Gtk.Label label41;

		private global::Gtk.Label label43;

		private global::Gtk.Label label45;

		private global::Gtk.VBox vbox44;

		private global::Gtk.Entry NombreAlumno;

		private global::Gtk.Entry ApellidoAlumno;

		private global::Gtk.Entry EdadAlumno;

		private global::Gtk.VBox vbox46;

		private global::Gtk.Label label47;

		private global::Gtk.Label label49;

		private global::Gtk.Label label51;

		private global::Gtk.VBox vbox48;

		private global::Gtk.Entry DescripcionAlumno;

		private global::Gtk.Entry CarreraAlumno;

		private global::Gtk.Entry AnoAlumno;

		private global::Gtk.VBox vbox50;

		private global::Gtk.Label label53;

		private global::Gtk.VBox vbox52;

		private global::Gtk.Label label57;

		private global::Gtk.Entry RutAlumno;

		private global::Gtk.Button VolverAlumno;

		private global::Gtk.Label UsuarioAlumno;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget gtk.ThirdWindow
			this.Name = "gtk.ThirdWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("ThirdWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child gtk.ThirdWindow.Gtk.Container+ContainerChild
			this.notebook5 = new global::Gtk.Notebook();
			this.notebook5.CanFocus = true;
			this.notebook5.Name = "notebook5";
			this.notebook5.CurrentPage = 0;
			// Container child notebook5.Gtk.Notebook+NotebookChild
			this.table2 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.IngresarProfesor = new global::Gtk.Button();
			this.IngresarProfesor.CanFocus = true;
			this.IngresarProfesor.Name = "IngresarProfesor";
			this.IngresarProfesor.UseUnderline = true;
			this.IngresarProfesor.Label = global::Mono.Unix.Catalog.GetString("Ingresar");
			this.table2.Add(this.IngresarProfesor);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2[this.IngresarProfesor]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(2));
			w1.RightAttach = ((uint)(3));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label37 = new global::Gtk.Label();
			this.label37.Name = "label37";
			this.label37.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario Profesor");
			this.table2.Add(this.label37);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2[this.label37]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.RegistradoProfesor = new global::Gtk.Button();
			this.RegistradoProfesor.CanFocus = true;
			this.RegistradoProfesor.Name = "RegistradoProfesor";
			this.RegistradoProfesor.UseUnderline = true;
			this.RegistradoProfesor.Label = global::Mono.Unix.Catalog.GetString("Estoy Registrado");
			this.table2.Add(this.RegistradoProfesor);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2[this.RegistradoProfesor]));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.vbox23 = new global::Gtk.VBox();
			this.vbox23.Name = "vbox23";
			this.vbox23.Spacing = 6;
			// Container child vbox23.Gtk.Box+BoxChild
			this.Label28 = new global::Gtk.Label();
			this.Label28.Name = "Label28";
			this.Label28.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre");
			this.vbox23.Add(this.Label28);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox23[this.Label28]));
			w4.Position = 0;
			w4.Fill = false;
			// Container child vbox23.Gtk.Box+BoxChild
			this.label29 = new global::Gtk.Label();
			this.label29.Name = "label29";
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("Apellido");
			this.vbox23.Add(this.label29);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox23[this.label29]));
			w5.Position = 1;
			w5.Fill = false;
			// Container child vbox23.Gtk.Box+BoxChild
			this.label31 = new global::Gtk.Label();
			this.label31.Name = "label31";
			this.label31.LabelProp = global::Mono.Unix.Catalog.GetString("Edad");
			this.vbox23.Add(this.label31);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox23[this.label31]));
			w6.Position = 2;
			w6.Fill = false;
			this.table2.Add(this.vbox23);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2[this.vbox23]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.vbox25 = new global::Gtk.VBox();
			this.vbox25.Name = "vbox25";
			this.vbox25.Spacing = 6;
			// Container child vbox25.Gtk.Box+BoxChild
			this.NombreProfesor = new global::Gtk.Entry();
			this.NombreProfesor.CanFocus = true;
			this.NombreProfesor.Name = "NombreProfesor";
			this.NombreProfesor.IsEditable = true;
			this.NombreProfesor.InvisibleChar = '●';
			this.vbox25.Add(this.NombreProfesor);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.NombreProfesor]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox25.Gtk.Box+BoxChild
			this.ApellidoProfesor = new global::Gtk.Entry();
			this.ApellidoProfesor.CanFocus = true;
			this.ApellidoProfesor.Name = "ApellidoProfesor";
			this.ApellidoProfesor.IsEditable = true;
			this.ApellidoProfesor.InvisibleChar = '●';
			this.vbox25.Add(this.ApellidoProfesor);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.ApellidoProfesor]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox25.Gtk.Box+BoxChild
			this.EdadProfesor = new global::Gtk.Entry();
			this.EdadProfesor.CanFocus = true;
			this.EdadProfesor.Name = "EdadProfesor";
			this.EdadProfesor.IsEditable = true;
			this.EdadProfesor.InvisibleChar = '●';
			this.vbox25.Add(this.EdadProfesor);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.EdadProfesor]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.table2.Add(this.vbox25);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2[this.vbox25]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.vbox29 = new global::Gtk.VBox();
			this.vbox29.Name = "vbox29";
			this.vbox29.Spacing = 6;
			// Container child vbox29.Gtk.Box+BoxChild
			this.label33 = new global::Gtk.Label();
			this.label33.Name = "label33";
			this.label33.LabelProp = global::Mono.Unix.Catalog.GetString("Descripcion sobre usted");
			this.vbox29.Add(this.label33);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox29[this.label33]));
			w12.Position = 0;
			w12.Fill = false;
			// Container child vbox29.Gtk.Box+BoxChild
			this.label35 = new global::Gtk.Label();
			this.label35.Name = "label35";
			this.label35.LabelProp = global::Mono.Unix.Catalog.GetString("Especialidad");
			this.vbox29.Add(this.label35);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox29[this.label35]));
			w13.Position = 1;
			// Container child vbox29.Gtk.Box+BoxChild
			this.label39 = new global::Gtk.Label();
			this.label39.Name = "label39";
			this.label39.LabelProp = global::Mono.Unix.Catalog.GetString("Rut");
			this.vbox29.Add(this.label39);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox29[this.label39]));
			w14.Position = 2;
			w14.Fill = false;
			this.table2.Add(this.vbox29);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2[this.vbox29]));
			w15.TopAttach = ((uint)(2));
			w15.BottomAttach = ((uint)(3));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.vbox31 = new global::Gtk.VBox();
			this.vbox31.Name = "vbox31";
			this.vbox31.Spacing = 6;
			// Container child vbox31.Gtk.Box+BoxChild
			this.DescripcionProfesor = new global::Gtk.Entry();
			this.DescripcionProfesor.CanFocus = true;
			this.DescripcionProfesor.Name = "DescripcionProfesor";
			this.DescripcionProfesor.IsEditable = true;
			this.DescripcionProfesor.InvisibleChar = '●';
			this.vbox31.Add(this.DescripcionProfesor);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.DescripcionProfesor]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox31.Gtk.Box+BoxChild
			this.EspecialidadProfesor = new global::Gtk.Entry();
			this.EspecialidadProfesor.CanFocus = true;
			this.EspecialidadProfesor.Name = "EspecialidadProfesor";
			this.EspecialidadProfesor.IsEditable = true;
			this.EspecialidadProfesor.InvisibleChar = '●';
			this.vbox31.Add(this.EspecialidadProfesor);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.EspecialidadProfesor]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox31.Gtk.Box+BoxChild
			this.RutProfesor = new global::Gtk.Entry();
			this.RutProfesor.CanFocus = true;
			this.RutProfesor.Name = "RutProfesor";
			this.RutProfesor.IsEditable = true;
			this.RutProfesor.InvisibleChar = '●';
			this.vbox31.Add(this.RutProfesor);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.RutProfesor]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			this.table2.Add(this.vbox31);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table2[this.vbox31]));
			w19.TopAttach = ((uint)(2));
			w19.BottomAttach = ((uint)(3));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.VolverProfesor = new global::Gtk.Button();
			this.VolverProfesor.CanFocus = true;
			this.VolverProfesor.Name = "VolverProfesor";
			this.VolverProfesor.UseUnderline = true;
			this.VolverProfesor.Label = global::Mono.Unix.Catalog.GetString("Volver");
			this.table2.Add(this.VolverProfesor);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2[this.VolverProfesor]));
			w20.TopAttach = ((uint)(2));
			w20.BottomAttach = ((uint)(3));
			w20.LeftAttach = ((uint)(2));
			w20.RightAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook5.Add(this.table2);
			// Notebook tab
			this.UsuarioProfesor = new global::Gtk.Label();
			this.UsuarioProfesor.Name = "UsuarioProfesor";
			this.UsuarioProfesor.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario Profesor");
			this.notebook5.SetTabLabel(this.table2, this.UsuarioProfesor);
			this.UsuarioProfesor.ShowAll();
			// Container child notebook5.Gtk.Notebook+NotebookChild
			this.table5 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.IngresarAlumno = new global::Gtk.Button();
			this.IngresarAlumno.CanFocus = true;
			this.IngresarAlumno.Name = "IngresarAlumno";
			this.IngresarAlumno.UseUnderline = true;
			this.IngresarAlumno.Label = global::Mono.Unix.Catalog.GetString("Ingresar");
			this.table5.Add(this.IngresarAlumno);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table5[this.IngresarAlumno]));
			w22.TopAttach = ((uint)(1));
			w22.BottomAttach = ((uint)(2));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(3));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.RegistradoAlumno = new global::Gtk.Button();
			this.RegistradoAlumno.CanFocus = true;
			this.RegistradoAlumno.Name = "RegistradoAlumno";
			this.RegistradoAlumno.UseUnderline = true;
			this.RegistradoAlumno.Label = global::Mono.Unix.Catalog.GetString("Estoy Registrado");
			this.table5.Add(this.RegistradoAlumno);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table5[this.RegistradoAlumno]));
			w23.LeftAttach = ((uint)(2));
			w23.RightAttach = ((uint)(3));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.vbox42 = new global::Gtk.VBox();
			this.vbox42.Name = "vbox42";
			this.vbox42.Spacing = 6;
			// Container child vbox42.Gtk.Box+BoxChild
			this.label41 = new global::Gtk.Label();
			this.label41.Name = "label41";
			this.label41.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre");
			this.vbox42.Add(this.label41);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox42[this.label41]));
			w24.Position = 0;
			w24.Fill = false;
			// Container child vbox42.Gtk.Box+BoxChild
			this.label43 = new global::Gtk.Label();
			this.label43.Name = "label43";
			this.label43.LabelProp = global::Mono.Unix.Catalog.GetString("Apellido");
			this.vbox42.Add(this.label43);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox42[this.label43]));
			w25.Position = 1;
			w25.Fill = false;
			// Container child vbox42.Gtk.Box+BoxChild
			this.label45 = new global::Gtk.Label();
			this.label45.Name = "label45";
			this.label45.LabelProp = global::Mono.Unix.Catalog.GetString("Edad");
			this.vbox42.Add(this.label45);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox42[this.label45]));
			w26.Position = 2;
			w26.Fill = false;
			this.table5.Add(this.vbox42);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table5[this.vbox42]));
			w27.TopAttach = ((uint)(1));
			w27.BottomAttach = ((uint)(2));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.vbox44 = new global::Gtk.VBox();
			this.vbox44.Name = "vbox44";
			this.vbox44.Spacing = 6;
			// Container child vbox44.Gtk.Box+BoxChild
			this.NombreAlumno = new global::Gtk.Entry();
			this.NombreAlumno.CanFocus = true;
			this.NombreAlumno.Name = "NombreAlumno";
			this.NombreAlumno.IsEditable = true;
			this.NombreAlumno.InvisibleChar = '●';
			this.vbox44.Add(this.NombreAlumno);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox44[this.NombreAlumno]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox44.Gtk.Box+BoxChild
			this.ApellidoAlumno = new global::Gtk.Entry();
			this.ApellidoAlumno.CanFocus = true;
			this.ApellidoAlumno.Name = "ApellidoAlumno";
			this.ApellidoAlumno.IsEditable = true;
			this.ApellidoAlumno.InvisibleChar = '●';
			this.vbox44.Add(this.ApellidoAlumno);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox44[this.ApellidoAlumno]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox44.Gtk.Box+BoxChild
			this.EdadAlumno = new global::Gtk.Entry();
			this.EdadAlumno.CanFocus = true;
			this.EdadAlumno.Name = "EdadAlumno";
			this.EdadAlumno.IsEditable = true;
			this.EdadAlumno.InvisibleChar = '●';
			this.vbox44.Add(this.EdadAlumno);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox44[this.EdadAlumno]));
			w30.Position = 2;
			w30.Expand = false;
			w30.Fill = false;
			this.table5.Add(this.vbox44);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table5[this.vbox44]));
			w31.TopAttach = ((uint)(1));
			w31.BottomAttach = ((uint)(2));
			w31.LeftAttach = ((uint)(1));
			w31.RightAttach = ((uint)(2));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.vbox46 = new global::Gtk.VBox();
			this.vbox46.Name = "vbox46";
			this.vbox46.Spacing = 6;
			// Container child vbox46.Gtk.Box+BoxChild
			this.label47 = new global::Gtk.Label();
			this.label47.Name = "label47";
			this.label47.LabelProp = global::Mono.Unix.Catalog.GetString("Descripcion sobre usted");
			this.vbox46.Add(this.label47);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox46[this.label47]));
			w32.Position = 0;
			w32.Fill = false;
			// Container child vbox46.Gtk.Box+BoxChild
			this.label49 = new global::Gtk.Label();
			this.label49.Name = "label49";
			this.label49.LabelProp = global::Mono.Unix.Catalog.GetString("Carrera");
			this.vbox46.Add(this.label49);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox46[this.label49]));
			w33.Position = 1;
			w33.Fill = false;
			// Container child vbox46.Gtk.Box+BoxChild
			this.label51 = new global::Gtk.Label();
			this.label51.Name = "label51";
			this.label51.LabelProp = global::Mono.Unix.Catalog.GetString("Año");
			this.vbox46.Add(this.label51);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox46[this.label51]));
			w34.Position = 2;
			w34.Fill = false;
			this.table5.Add(this.vbox46);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table5[this.vbox46]));
			w35.TopAttach = ((uint)(2));
			w35.BottomAttach = ((uint)(3));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.vbox48 = new global::Gtk.VBox();
			this.vbox48.Name = "vbox48";
			this.vbox48.Spacing = 6;
			// Container child vbox48.Gtk.Box+BoxChild
			this.DescripcionAlumno = new global::Gtk.Entry();
			this.DescripcionAlumno.CanFocus = true;
			this.DescripcionAlumno.Name = "DescripcionAlumno";
			this.DescripcionAlumno.IsEditable = true;
			this.DescripcionAlumno.InvisibleChar = '●';
			this.vbox48.Add(this.DescripcionAlumno);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox48[this.DescripcionAlumno]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox48.Gtk.Box+BoxChild
			this.CarreraAlumno = new global::Gtk.Entry();
			this.CarreraAlumno.CanFocus = true;
			this.CarreraAlumno.Name = "CarreraAlumno";
			this.CarreraAlumno.IsEditable = true;
			this.CarreraAlumno.InvisibleChar = '●';
			this.vbox48.Add(this.CarreraAlumno);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox48[this.CarreraAlumno]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox48.Gtk.Box+BoxChild
			this.AnoAlumno = new global::Gtk.Entry();
			this.AnoAlumno.CanFocus = true;
			this.AnoAlumno.Name = "AnoAlumno";
			this.AnoAlumno.IsEditable = true;
			this.AnoAlumno.InvisibleChar = '●';
			this.vbox48.Add(this.AnoAlumno);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox48[this.AnoAlumno]));
			w38.Position = 2;
			w38.Expand = false;
			w38.Fill = false;
			this.table5.Add(this.vbox48);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table5[this.vbox48]));
			w39.TopAttach = ((uint)(2));
			w39.BottomAttach = ((uint)(3));
			w39.LeftAttach = ((uint)(1));
			w39.RightAttach = ((uint)(2));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.vbox50 = new global::Gtk.VBox();
			this.vbox50.Name = "vbox50";
			this.vbox50.Spacing = 6;
			// Container child vbox50.Gtk.Box+BoxChild
			this.label53 = new global::Gtk.Label();
			this.label53.Name = "label53";
			this.label53.LabelProp = global::Mono.Unix.Catalog.GetString("Rut");
			this.vbox50.Add(this.label53);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox50[this.label53]));
			w40.Position = 1;
			w40.Fill = false;
			this.table5.Add(this.vbox50);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table5[this.vbox50]));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.vbox52 = new global::Gtk.VBox();
			this.vbox52.Name = "vbox52";
			this.vbox52.Spacing = 6;
			// Container child vbox52.Gtk.Box+BoxChild
			this.label57 = new global::Gtk.Label();
			this.label57.Name = "label57";
			this.label57.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario Alumno");
			this.vbox52.Add(this.label57);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox52[this.label57]));
			w42.Position = 0;
			// Container child vbox52.Gtk.Box+BoxChild
			this.RutAlumno = new global::Gtk.Entry();
			this.RutAlumno.CanFocus = true;
			this.RutAlumno.Name = "RutAlumno";
			this.RutAlumno.IsEditable = true;
			this.RutAlumno.InvisibleChar = '●';
			this.vbox52.Add(this.RutAlumno);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox52[this.RutAlumno]));
			w43.Position = 1;
			w43.Expand = false;
			w43.Fill = false;
			this.table5.Add(this.vbox52);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table5[this.vbox52]));
			w44.LeftAttach = ((uint)(1));
			w44.RightAttach = ((uint)(2));
			w44.XOptions = ((global::Gtk.AttachOptions)(4));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.VolverAlumno = new global::Gtk.Button();
			this.VolverAlumno.CanFocus = true;
			this.VolverAlumno.Name = "VolverAlumno";
			this.VolverAlumno.UseUnderline = true;
			this.VolverAlumno.Label = global::Mono.Unix.Catalog.GetString("Volver");
			this.table5.Add(this.VolverAlumno);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table5[this.VolverAlumno]));
			w45.TopAttach = ((uint)(2));
			w45.BottomAttach = ((uint)(3));
			w45.LeftAttach = ((uint)(2));
			w45.RightAttach = ((uint)(3));
			w45.XOptions = ((global::Gtk.AttachOptions)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook5.Add(this.table5);
			global::Gtk.Notebook.NotebookChild w46 = ((global::Gtk.Notebook.NotebookChild)(this.notebook5[this.table5]));
			w46.Position = 1;
			// Notebook tab
			this.UsuarioAlumno = new global::Gtk.Label();
			this.UsuarioAlumno.Name = "UsuarioAlumno";
			this.UsuarioAlumno.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario Alumno");
			this.notebook5.SetTabLabel(this.table5, this.UsuarioAlumno);
			this.UsuarioAlumno.ShowAll();
			this.Add(this.notebook5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 639;
			this.DefaultHeight = 300;
			this.Show();
			this.VolverProfesor.Clicked += new global::System.EventHandler(this.OnVolverProfesorClicked);
			this.RegistradoProfesor.Clicked += new global::System.EventHandler(this.OnRegistradoProfesorClicked);
			this.IngresarProfesor.Clicked += new global::System.EventHandler(this.OnIngresarClicked);
			this.VolverAlumno.Clicked += new global::System.EventHandler(this.OnVolverAlumnoClicked);
			this.RegistradoAlumno.Clicked += new global::System.EventHandler(this.OnRegistradoAlumnoClicked);
			this.IngresarAlumno.Clicked += new global::System.EventHandler(this.OnButton21Clicked);
		}
	}
}
