
// This file has been generated by the GUI designer. Do not modify.
namespace gtk
{
	public partial class SecondWindow
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label4;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button Si;

		private global::Gtk.Button No;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget gtk.SecondWindow
			this.Name = "gtk.SecondWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("SecondWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child gtk.SecondWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("¿Es usuario nuevo?");
			this.vbox2.Add(this.label4);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label4]));
			w1.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.Si = new global::Gtk.Button();
			this.Si.CanFocus = true;
			this.Si.Name = "Si";
			this.Si.UseUnderline = true;
			this.Si.Label = global::Mono.Unix.Catalog.GetString("Si");
			this.hbox1.Add(this.Si);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Si]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.No = new global::Gtk.Button();
			this.No.CanFocus = true;
			this.No.Name = "No";
			this.No.UseUnderline = true;
			this.No.Label = global::Mono.Unix.Catalog.GetString("No");
			this.hbox1.Add(this.No);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.No]));
			w3.Position = 1;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.Si.Clicked += new global::System.EventHandler(this.OnSiClicked);
			this.No.Clicked += new global::System.EventHandler(this.OnNoClicked);
		}
	}
}
