
// This file has been generated by the GUI designer. Do not modify.
namespace gtk
{
	public partial class FifthWindow
	{
		private global::Gtk.Notebook notebook6;

		private global::Gtk.HBox hbox13;

		private global::Gtk.Alignment alignment4;

		private global::Gtk.HPaned hpaned3;

		private global::Gtk.VPaned vpaned3;

		private global::Gtk.Table table24;

		private global::Gtk.Button IngresarOferta;

		private global::Gtk.Table table28;

		private global::Gtk.Label label150;

		private global::Gtk.Label label152;

		private global::Gtk.Label label154;

		private global::Gtk.Entry Remuneracion1;

		private global::Gtk.Entry Titulo1;

		private global::Gtk.Entry Vacantes1;

		private global::Gtk.Table table30;

		private global::Gtk.Entry Descripcion1;

		private global::Gtk.Label label156;

		private global::Gtk.Label label158;

		private global::Gtk.Label label160;

		private global::Gtk.Entry Lugar1;

		private global::Gtk.Table table32;

		private global::Gtk.Entry Inicio1;

		private global::Gtk.Label label162;

		private global::Gtk.Label label164;

		private global::Gtk.Entry Termino1;

		private global::Gtk.VBox vbox126;

		private global::Gtk.Label label170;

		private global::Gtk.Label Label166;

		private global::Gtk.Label label168;

		private global::Gtk.VBox vbox128;

		private global::Gtk.CheckButton Investigacion1;

		private global::Gtk.Entry Area1;

		private global::Gtk.Entry Especialidad1;

		private global::Gtk.VBox vbox130;

		private global::Gtk.Label label172;

		private global::Gtk.Label label174;

		private global::Gtk.Label label61;

		private global::Gtk.Table table34;

		private global::Gtk.Button button40;

		private global::Gtk.Entry CodigoPostulacion2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textview10;

		private global::Gtk.Label label178;

		private global::Gtk.Button VerOfertas;

		private global::Gtk.Label label62;

		private global::Gtk.Table table8;

		private global::Gtk.Button AceptarPostulante;

		private global::Gtk.ScrolledWindow GtkScrolledWindow2;

		private global::Gtk.TextView textview8;

		private global::Gtk.ScrolledWindow GtkScrolledWindow7;

		private global::Gtk.TextView textview2;

		private global::Gtk.Label rc;

		private global::Gtk.Entry rutcontratado;

		private global::Gtk.VBox vbox55;

		private global::Gtk.Label label193;

		private global::Gtk.VBox vbox57;

		private global::Gtk.Entry CodigoOferta3;

		private global::Gtk.VBox vbox61;

		private global::Gtk.Button VerOfertas3;

		private global::Gtk.Button VerPostulantes;

		private global::Gtk.Label label63;

		private global::Gtk.Table table35;

		private global::Gtk.Entry CodigoOferta4;

		private global::Gtk.Button DarDeBaja;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TextView textview12;

		private global::Gtk.Label label180;

		private global::Gtk.Button VerBajables;

		private global::Gtk.Label label64;

		private global::Gtk.Table table36;

		private global::Gtk.Button button1;

		private global::Gtk.Entry CodigoOferta5;

		private global::Gtk.Entry Estrellas5;

		private global::Gtk.ScrolledWindow GtkScrolledWindow3;

		private global::Gtk.TextView textview14;

		private global::Gtk.Label label183;

		private global::Gtk.Label label185;

		private global::Gtk.Button Rankear;

		private global::Gtk.Label label65;

		private global::Gtk.Table table37;

		private global::Gtk.Entry CodigoOferta6;

		private global::Gtk.Entry Comentario6;

		private global::Gtk.ScrolledWindow GtkScrolledWindow4;

		private global::Gtk.TextView textview15;

		private global::Gtk.Button IngresarComentario;

		private global::Gtk.Label label187;

		private global::Gtk.Label label189;

		private global::Gtk.Button VerComentables;

		private global::Gtk.Label label182;

		private global::Gtk.Table table2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow5;

		private global::Gtk.TextView textview16;

		private global::Gtk.ScrolledWindow GtkScrolledWindow6;

		private global::Gtk.TextView textview18;

		private global::Gtk.Button VerMisOfertas;

		private global::Gtk.Button VerOfertasAceptadas;

		private global::Gtk.Label label1;

		private global::Gtk.Table table38;

		private global::Gtk.Button ApagarPrograma;

		private global::Gtk.Button CerrarSesion;

		private global::Gtk.Label label66;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget gtk.FifthWindow
			this.Name = "gtk.FifthWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("FifthWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child gtk.FifthWindow.Gtk.Container+ContainerChild
			this.notebook6 = new global::Gtk.Notebook();
			this.notebook6.CanFocus = true;
			this.notebook6.Name = "notebook6";
			this.notebook6.CurrentPage = 2;
			// Container child notebook6.Gtk.Notebook+NotebookChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			// Container child alignment4.Gtk.Container+ContainerChild
			this.hpaned3 = new global::Gtk.HPaned();
			this.hpaned3.CanFocus = true;
			this.hpaned3.Name = "hpaned3";
			this.hpaned3.Position = 10;
			// Container child hpaned3.Gtk.Paned+PanedChild
			this.vpaned3 = new global::Gtk.VPaned();
			this.vpaned3.CanFocus = true;
			this.vpaned3.Name = "vpaned3";
			this.vpaned3.Position = 10;
			// Container child vpaned3.Gtk.Paned+PanedChild
			this.table24 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table24.Name = "table24";
			this.table24.RowSpacing = ((uint)(6));
			this.table24.ColumnSpacing = ((uint)(6));
			// Container child table24.Gtk.Table+TableChild
			this.IngresarOferta = new global::Gtk.Button();
			this.IngresarOferta.CanFocus = true;
			this.IngresarOferta.Name = "IngresarOferta";
			this.IngresarOferta.UseUnderline = true;
			this.IngresarOferta.Label = global::Mono.Unix.Catalog.GetString("Ingresar Oferta/Investigacion");
			this.table24.Add(this.IngresarOferta);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table24[this.IngresarOferta]));
			w1.TopAttach = ((uint)(2));
			w1.BottomAttach = ((uint)(3));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table24.Gtk.Table+TableChild
			this.table28 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table28.Name = "table28";
			this.table28.RowSpacing = ((uint)(6));
			this.table28.ColumnSpacing = ((uint)(6));
			// Container child table28.Gtk.Table+TableChild
			this.label150 = new global::Gtk.Label();
			this.label150.Name = "label150";
			this.label150.LabelProp = global::Mono.Unix.Catalog.GetString("Título");
			this.table28.Add(this.label150);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table28[this.label150]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table28.Gtk.Table+TableChild
			this.label152 = new global::Gtk.Label();
			this.label152.Name = "label152";
			this.label152.LabelProp = global::Mono.Unix.Catalog.GetString("Remuneración");
			this.table28.Add(this.label152);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table28[this.label152]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table28.Gtk.Table+TableChild
			this.label154 = new global::Gtk.Label();
			this.label154.Name = "label154";
			this.label154.LabelProp = global::Mono.Unix.Catalog.GetString("Vacantes");
			this.table28.Add(this.label154);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table28[this.label154]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table28.Gtk.Table+TableChild
			this.Remuneracion1 = new global::Gtk.Entry();
			this.Remuneracion1.CanFocus = true;
			this.Remuneracion1.Name = "Remuneracion1";
			this.Remuneracion1.IsEditable = true;
			this.Remuneracion1.InvisibleChar = '●';
			this.table28.Add(this.Remuneracion1);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table28[this.Remuneracion1]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table28.Gtk.Table+TableChild
			this.Titulo1 = new global::Gtk.Entry();
			this.Titulo1.CanFocus = true;
			this.Titulo1.Name = "Titulo1";
			this.Titulo1.IsEditable = true;
			this.Titulo1.InvisibleChar = '●';
			this.table28.Add(this.Titulo1);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table28[this.Titulo1]));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table28.Gtk.Table+TableChild
			this.Vacantes1 = new global::Gtk.Entry();
			this.Vacantes1.CanFocus = true;
			this.Vacantes1.Name = "Vacantes1";
			this.Vacantes1.IsEditable = true;
			this.Vacantes1.InvisibleChar = '●';
			this.table28.Add(this.Vacantes1);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table28[this.Vacantes1]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table24.Add(this.table28);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table24[this.table28]));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table24.Gtk.Table+TableChild
			this.table30 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table30.Name = "table30";
			this.table30.RowSpacing = ((uint)(6));
			this.table30.ColumnSpacing = ((uint)(6));
			// Container child table30.Gtk.Table+TableChild
			this.Descripcion1 = new global::Gtk.Entry();
			this.Descripcion1.CanFocus = true;
			this.Descripcion1.Name = "Descripcion1";
			this.Descripcion1.IsEditable = true;
			this.Descripcion1.InvisibleChar = '●';
			this.table30.Add(this.Descripcion1);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table30[this.Descripcion1]));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table30.Gtk.Table+TableChild
			this.label156 = new global::Gtk.Label();
			this.label156.Name = "label156";
			this.label156.LabelProp = global::Mono.Unix.Catalog.GetString("Descripción");
			this.table30.Add(this.label156);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table30[this.label156]));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table30.Gtk.Table+TableChild
			this.label158 = new global::Gtk.Label();
			this.label158.Name = "label158";
			this.label158.LabelProp = global::Mono.Unix.Catalog.GetString("Para el evento:");
			this.table30.Add(this.label158);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table30[this.label158]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table30.Gtk.Table+TableChild
			this.label160 = new global::Gtk.Label();
			this.label160.Name = "label160";
			this.label160.LabelProp = global::Mono.Unix.Catalog.GetString("Lugar");
			this.table30.Add(this.label160);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table30[this.label160]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table30.Gtk.Table+TableChild
			this.Lugar1 = new global::Gtk.Entry();
			this.Lugar1.CanFocus = true;
			this.Lugar1.Name = "Lugar1";
			this.Lugar1.IsEditable = true;
			this.Lugar1.InvisibleChar = '●';
			this.table30.Add(this.Lugar1);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table30[this.Lugar1]));
			w13.TopAttach = ((uint)(2));
			w13.BottomAttach = ((uint)(3));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table24.Add(this.table30);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table24[this.table30]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table24.Gtk.Table+TableChild
			this.table32 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table32.Name = "table32";
			this.table32.RowSpacing = ((uint)(6));
			this.table32.ColumnSpacing = ((uint)(6));
			// Container child table32.Gtk.Table+TableChild
			this.Inicio1 = new global::Gtk.Entry();
			this.Inicio1.CanFocus = true;
			this.Inicio1.Name = "Inicio1";
			this.Inicio1.Text = global::Mono.Unix.Catalog.GetString("DD/MM/AAAA");
			this.Inicio1.IsEditable = true;
			this.Inicio1.InvisibleChar = '●';
			this.table32.Add(this.Inicio1);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table32[this.Inicio1]));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table32.Gtk.Table+TableChild
			this.label162 = new global::Gtk.Label();
			this.label162.Name = "label162";
			this.label162.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha Inicio");
			this.table32.Add(this.label162);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table32[this.label162]));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table32.Gtk.Table+TableChild
			this.label164 = new global::Gtk.Label();
			this.label164.Name = "label164";
			this.label164.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha Término");
			this.table32.Add(this.label164);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table32[this.label164]));
			w17.TopAttach = ((uint)(1));
			w17.BottomAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table32.Gtk.Table+TableChild
			this.Termino1 = new global::Gtk.Entry();
			this.Termino1.CanFocus = true;
			this.Termino1.Name = "Termino1";
			this.Termino1.Text = global::Mono.Unix.Catalog.GetString("DD/MM/AAAA");
			this.Termino1.IsEditable = true;
			this.Termino1.InvisibleChar = '●';
			this.table32.Add(this.Termino1);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table32[this.Termino1]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table32.Gtk.Table+TableChild
			this.vbox126 = new global::Gtk.VBox();
			this.vbox126.Name = "vbox126";
			this.vbox126.Spacing = 6;
			// Container child vbox126.Gtk.Box+BoxChild
			this.label170 = new global::Gtk.Label();
			this.label170.Name = "label170";
			this.vbox126.Add(this.label170);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox126[this.label170]));
			w19.Position = 0;
			w19.Fill = false;
			// Container child vbox126.Gtk.Box+BoxChild
			this.Label166 = new global::Gtk.Label();
			this.Label166.Name = "Label166";
			this.Label166.LabelProp = global::Mono.Unix.Catalog.GetString("Área");
			this.vbox126.Add(this.Label166);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox126[this.Label166]));
			w20.Position = 1;
			w20.Fill = false;
			// Container child vbox126.Gtk.Box+BoxChild
			this.label168 = new global::Gtk.Label();
			this.label168.Name = "label168";
			this.label168.LabelProp = global::Mono.Unix.Catalog.GetString("Especialidad");
			this.vbox126.Add(this.label168);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox126[this.label168]));
			w21.Position = 2;
			w21.Fill = false;
			this.table32.Add(this.vbox126);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table32[this.vbox126]));
			w22.TopAttach = ((uint)(2));
			w22.BottomAttach = ((uint)(3));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table32.Gtk.Table+TableChild
			this.vbox128 = new global::Gtk.VBox();
			this.vbox128.Name = "vbox128";
			this.vbox128.Spacing = 6;
			// Container child vbox128.Gtk.Box+BoxChild
			this.Investigacion1 = new global::Gtk.CheckButton();
			this.Investigacion1.CanFocus = true;
			this.Investigacion1.Name = "Investigacion1";
			this.Investigacion1.Label = global::Mono.Unix.Catalog.GetString("Investigación");
			this.Investigacion1.DrawIndicator = true;
			this.Investigacion1.UseUnderline = true;
			this.vbox128.Add(this.Investigacion1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox128[this.Investigacion1]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox128.Gtk.Box+BoxChild
			this.Area1 = new global::Gtk.Entry();
			this.Area1.CanFocus = true;
			this.Area1.Name = "Area1";
			this.Area1.IsEditable = true;
			this.Area1.InvisibleChar = '●';
			this.vbox128.Add(this.Area1);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox128[this.Area1]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox128.Gtk.Box+BoxChild
			this.Especialidad1 = new global::Gtk.Entry();
			this.Especialidad1.CanFocus = true;
			this.Especialidad1.Name = "Especialidad1";
			this.Especialidad1.IsEditable = true;
			this.Especialidad1.InvisibleChar = '●';
			this.vbox128.Add(this.Especialidad1);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox128[this.Especialidad1]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			this.table32.Add(this.vbox128);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table32[this.vbox128]));
			w26.TopAttach = ((uint)(2));
			w26.BottomAttach = ((uint)(3));
			w26.LeftAttach = ((uint)(1));
			w26.RightAttach = ((uint)(2));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table32.Gtk.Table+TableChild
			this.vbox130 = new global::Gtk.VBox();
			this.vbox130.Name = "vbox130";
			this.vbox130.Spacing = 6;
			// Container child vbox130.Gtk.Box+BoxChild
			this.label172 = new global::Gtk.Label();
			this.label172.Name = "label172";
			this.label172.LabelProp = global::Mono.Unix.Catalog.GetString("(Solamente si es Investigación)");
			this.vbox130.Add(this.label172);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox130[this.label172]));
			w27.Position = 1;
			w27.Fill = false;
			// Container child vbox130.Gtk.Box+BoxChild
			this.label174 = new global::Gtk.Label();
			this.label174.Name = "label174";
			this.label174.LabelProp = global::Mono.Unix.Catalog.GetString("(Solamente si es Investigación)");
			this.vbox130.Add(this.label174);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox130[this.label174]));
			w28.Position = 2;
			w28.Fill = false;
			this.table32.Add(this.vbox130);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table32[this.vbox130]));
			w29.TopAttach = ((uint)(2));
			w29.BottomAttach = ((uint)(3));
			w29.LeftAttach = ((uint)(2));
			w29.RightAttach = ((uint)(3));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			this.table24.Add(this.table32);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table24[this.table32]));
			w30.TopAttach = ((uint)(2));
			w30.BottomAttach = ((uint)(3));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vpaned3.Add(this.table24);
			this.hpaned3.Add(this.vpaned3);
			this.alignment4.Add(this.hpaned3);
			this.hbox13.Add(this.alignment4);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.alignment4]));
			w34.Position = 0;
			this.notebook6.Add(this.hbox13);
			// Notebook tab
			this.label61 = new global::Gtk.Label();
			this.label61.Name = "label61";
			this.label61.LabelProp = global::Mono.Unix.Catalog.GetString("Ingresar Oferta");
			this.notebook6.SetTabLabel(this.hbox13, this.label61);
			this.label61.ShowAll();
			// Container child notebook6.Gtk.Notebook+NotebookChild
			this.table34 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table34.Name = "table34";
			this.table34.RowSpacing = ((uint)(6));
			this.table34.ColumnSpacing = ((uint)(6));
			// Container child table34.Gtk.Table+TableChild
			this.button40 = new global::Gtk.Button();
			this.button40.CanFocus = true;
			this.button40.Name = "button40";
			this.button40.UseUnderline = true;
			this.button40.Label = global::Mono.Unix.Catalog.GetString("Ingresar Postulación");
			this.table34.Add(this.button40);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table34[this.button40]));
			w36.TopAttach = ((uint)(1));
			w36.BottomAttach = ((uint)(2));
			w36.LeftAttach = ((uint)(2));
			w36.RightAttach = ((uint)(3));
			w36.XOptions = ((global::Gtk.AttachOptions)(0));
			w36.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table34.Gtk.Table+TableChild
			this.CodigoPostulacion2 = new global::Gtk.Entry();
			this.CodigoPostulacion2.CanFocus = true;
			this.CodigoPostulacion2.Name = "CodigoPostulacion2";
			this.CodigoPostulacion2.IsEditable = true;
			this.CodigoPostulacion2.InvisibleChar = '●';
			this.table34.Add(this.CodigoPostulacion2);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table34[this.CodigoPostulacion2]));
			w37.TopAttach = ((uint)(1));
			w37.BottomAttach = ((uint)(2));
			w37.LeftAttach = ((uint)(1));
			w37.RightAttach = ((uint)(2));
			w37.XOptions = ((global::Gtk.AttachOptions)(0));
			w37.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table34.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview10 = new global::Gtk.TextView();
			this.textview10.CanFocus = true;
			this.textview10.Name = "textview10";
			this.GtkScrolledWindow.Add(this.textview10);
			this.table34.Add(this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table34[this.GtkScrolledWindow]));
			w39.TopAttach = ((uint)(2));
			w39.BottomAttach = ((uint)(3));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table34.Gtk.Table+TableChild
			this.label178 = new global::Gtk.Label();
			this.label178.Name = "label178";
			this.label178.LabelProp = global::Mono.Unix.Catalog.GetString("Ingrese el código de la oferta a la que quiere postular");
			this.table34.Add(this.label178);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table34[this.label178]));
			w40.TopAttach = ((uint)(1));
			w40.BottomAttach = ((uint)(2));
			w40.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table34.Gtk.Table+TableChild
			this.VerOfertas = new global::Gtk.Button();
			this.VerOfertas.CanFocus = true;
			this.VerOfertas.Name = "VerOfertas";
			this.VerOfertas.UseUnderline = true;
			this.VerOfertas.Label = global::Mono.Unix.Catalog.GetString("Ver Ofertas disponibles");
			this.table34.Add(this.VerOfertas);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table34[this.VerOfertas]));
			w41.LeftAttach = ((uint)(1));
			w41.RightAttach = ((uint)(2));
			w41.XOptions = ((global::Gtk.AttachOptions)(0));
			w41.YOptions = ((global::Gtk.AttachOptions)(0));
			this.notebook6.Add(this.table34);
			global::Gtk.Notebook.NotebookChild w42 = ((global::Gtk.Notebook.NotebookChild)(this.notebook6[this.table34]));
			w42.Position = 1;
			// Notebook tab
			this.label62 = new global::Gtk.Label();
			this.label62.Name = "label62";
			this.label62.LabelProp = global::Mono.Unix.Catalog.GetString("Postular a Oferta");
			this.notebook6.SetTabLabel(this.table34, this.label62);
			this.label62.ShowAll();
			// Container child notebook6.Gtk.Notebook+NotebookChild
			this.table8 = new global::Gtk.Table(((uint)(4)), ((uint)(3)), false);
			this.table8.Name = "table8";
			this.table8.RowSpacing = ((uint)(6));
			this.table8.ColumnSpacing = ((uint)(6));
			// Container child table8.Gtk.Table+TableChild
			this.AceptarPostulante = new global::Gtk.Button();
			this.AceptarPostulante.CanFocus = true;
			this.AceptarPostulante.Name = "AceptarPostulante";
			this.AceptarPostulante.UseUnderline = true;
			this.AceptarPostulante.Label = global::Mono.Unix.Catalog.GetString("Aceptar postulante");
			this.table8.Add(this.AceptarPostulante);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table8[this.AceptarPostulante]));
			w43.TopAttach = ((uint)(3));
			w43.BottomAttach = ((uint)(4));
			w43.LeftAttach = ((uint)(2));
			w43.RightAttach = ((uint)(3));
			w43.XOptions = ((global::Gtk.AttachOptions)(4));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.textview8 = new global::Gtk.TextView();
			this.textview8.CanFocus = true;
			this.textview8.Name = "textview8";
			this.GtkScrolledWindow2.Add(this.textview8);
			this.table8.Add(this.GtkScrolledWindow2);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table8[this.GtkScrolledWindow2]));
			w45.TopAttach = ((uint)(2));
			w45.BottomAttach = ((uint)(3));
			w45.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.GtkScrolledWindow7 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow7.Name = "GtkScrolledWindow7";
			this.GtkScrolledWindow7.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow7.Gtk.Container+ContainerChild
			this.textview2 = new global::Gtk.TextView();
			this.textview2.CanFocus = true;
			this.textview2.Name = "textview2";
			this.GtkScrolledWindow7.Add(this.textview2);
			this.table8.Add(this.GtkScrolledWindow7);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table8[this.GtkScrolledWindow7]));
			w47.TopAttach = ((uint)(2));
			w47.BottomAttach = ((uint)(3));
			w47.LeftAttach = ((uint)(1));
			w47.RightAttach = ((uint)(2));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.rc = new global::Gtk.Label();
			this.rc.Name = "rc";
			this.rc.LabelProp = global::Mono.Unix.Catalog.GetString("Ingrese el rut del usuario que desea aceptar");
			this.table8.Add(this.rc);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table8[this.rc]));
			w48.TopAttach = ((uint)(3));
			w48.BottomAttach = ((uint)(4));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.rutcontratado = new global::Gtk.Entry();
			this.rutcontratado.CanFocus = true;
			this.rutcontratado.Name = "rutcontratado";
			this.rutcontratado.IsEditable = true;
			this.rutcontratado.InvisibleChar = '●';
			this.table8.Add(this.rutcontratado);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table8[this.rutcontratado]));
			w49.TopAttach = ((uint)(3));
			w49.BottomAttach = ((uint)(4));
			w49.LeftAttach = ((uint)(1));
			w49.RightAttach = ((uint)(2));
			w49.XOptions = ((global::Gtk.AttachOptions)(4));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.vbox55 = new global::Gtk.VBox();
			this.vbox55.Name = "vbox55";
			this.vbox55.Spacing = 6;
			// Container child vbox55.Gtk.Box+BoxChild
			this.label193 = new global::Gtk.Label();
			this.label193.Name = "label193";
			this.label193.LabelProp = global::Mono.Unix.Catalog.GetString("Código Oferta");
			this.vbox55.Add(this.label193);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox55[this.label193]));
			w50.Position = 0;
			w50.Fill = false;
			this.table8.Add(this.vbox55);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.table8[this.vbox55]));
			w51.TopAttach = ((uint)(1));
			w51.BottomAttach = ((uint)(2));
			w51.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table8.Gtk.Table+TableChild
			this.vbox57 = new global::Gtk.VBox();
			this.vbox57.Name = "vbox57";
			this.vbox57.Spacing = 6;
			// Container child vbox57.Gtk.Box+BoxChild
			this.CodigoOferta3 = new global::Gtk.Entry();
			this.CodigoOferta3.CanFocus = true;
			this.CodigoOferta3.Name = "CodigoOferta3";
			this.CodigoOferta3.IsEditable = true;
			this.CodigoOferta3.InvisibleChar = '●';
			this.vbox57.Add(this.CodigoOferta3);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox57[this.CodigoOferta3]));
			w52.Position = 0;
			w52.Fill = false;
			this.table8.Add(this.vbox57);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table8[this.vbox57]));
			w53.TopAttach = ((uint)(1));
			w53.BottomAttach = ((uint)(2));
			w53.LeftAttach = ((uint)(1));
			w53.RightAttach = ((uint)(2));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.vbox61 = new global::Gtk.VBox();
			this.vbox61.Name = "vbox61";
			this.vbox61.Spacing = 6;
			// Container child vbox61.Gtk.Box+BoxChild
			this.VerOfertas3 = new global::Gtk.Button();
			this.VerOfertas3.CanFocus = true;
			this.VerOfertas3.Name = "VerOfertas3";
			this.VerOfertas3.UseUnderline = true;
			this.VerOfertas3.Label = global::Mono.Unix.Catalog.GetString("Ver sus Ofertas");
			this.vbox61.Add(this.VerOfertas3);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox61[this.VerOfertas3]));
			w54.Position = 0;
			w54.Fill = false;
			this.table8.Add(this.vbox61);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table8[this.vbox61]));
			w55.LeftAttach = ((uint)(1));
			w55.RightAttach = ((uint)(2));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table8.Gtk.Table+TableChild
			this.VerPostulantes = new global::Gtk.Button();
			this.VerPostulantes.CanFocus = true;
			this.VerPostulantes.Name = "VerPostulantes";
			this.VerPostulantes.UseUnderline = true;
			this.VerPostulantes.Label = global::Mono.Unix.Catalog.GetString("Ver Postulantes");
			this.table8.Add(this.VerPostulantes);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table8[this.VerPostulantes]));
			w56.TopAttach = ((uint)(1));
			w56.BottomAttach = ((uint)(2));
			w56.LeftAttach = ((uint)(2));
			w56.RightAttach = ((uint)(3));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook6.Add(this.table8);
			global::Gtk.Notebook.NotebookChild w57 = ((global::Gtk.Notebook.NotebookChild)(this.notebook6[this.table8]));
			w57.Position = 2;
			// Notebook tab
			this.label63 = new global::Gtk.Label();
			this.label63.Name = "label63";
			this.label63.LabelProp = global::Mono.Unix.Catalog.GetString("Aceptar Postulantes a Oferta");
			this.notebook6.SetTabLabel(this.table8, this.label63);
			this.label63.ShowAll();
			// Container child notebook6.Gtk.Notebook+NotebookChild
			this.table35 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table35.Name = "table35";
			this.table35.RowSpacing = ((uint)(6));
			this.table35.ColumnSpacing = ((uint)(6));
			// Container child table35.Gtk.Table+TableChild
			this.CodigoOferta4 = new global::Gtk.Entry();
			this.CodigoOferta4.CanFocus = true;
			this.CodigoOferta4.Name = "CodigoOferta4";
			this.CodigoOferta4.IsEditable = true;
			this.CodigoOferta4.InvisibleChar = '●';
			this.table35.Add(this.CodigoOferta4);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table35[this.CodigoOferta4]));
			w58.TopAttach = ((uint)(1));
			w58.BottomAttach = ((uint)(2));
			w58.LeftAttach = ((uint)(1));
			w58.RightAttach = ((uint)(2));
			w58.XOptions = ((global::Gtk.AttachOptions)(0));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table35.Gtk.Table+TableChild
			this.DarDeBaja = new global::Gtk.Button();
			this.DarDeBaja.CanFocus = true;
			this.DarDeBaja.Name = "DarDeBaja";
			this.DarDeBaja.UseUnderline = true;
			this.DarDeBaja.Label = global::Mono.Unix.Catalog.GetString("Dar de baja Oferta");
			this.table35.Add(this.DarDeBaja);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table35[this.DarDeBaja]));
			w59.TopAttach = ((uint)(1));
			w59.BottomAttach = ((uint)(2));
			w59.LeftAttach = ((uint)(2));
			w59.RightAttach = ((uint)(3));
			w59.XOptions = ((global::Gtk.AttachOptions)(0));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table35.Gtk.Table+TableChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.textview12 = new global::Gtk.TextView();
			this.textview12.CanFocus = true;
			this.textview12.Name = "textview12";
			this.GtkScrolledWindow1.Add(this.textview12);
			this.table35.Add(this.GtkScrolledWindow1);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.table35[this.GtkScrolledWindow1]));
			w61.TopAttach = ((uint)(2));
			w61.BottomAttach = ((uint)(3));
			w61.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table35.Gtk.Table+TableChild
			this.label180 = new global::Gtk.Label();
			this.label180.Name = "label180";
			this.label180.LabelProp = global::Mono.Unix.Catalog.GetString("Ingrese el código de la oferta que desea dar de baja");
			this.table35.Add(this.label180);
			global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.table35[this.label180]));
			w62.TopAttach = ((uint)(1));
			w62.BottomAttach = ((uint)(2));
			w62.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table35.Gtk.Table+TableChild
			this.VerBajables = new global::Gtk.Button();
			this.VerBajables.CanFocus = true;
			this.VerBajables.Name = "VerBajables";
			this.VerBajables.UseUnderline = true;
			this.VerBajables.Label = global::Mono.Unix.Catalog.GetString("Ver Ofertas");
			this.table35.Add(this.VerBajables);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.table35[this.VerBajables]));
			w63.LeftAttach = ((uint)(1));
			w63.RightAttach = ((uint)(2));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook6.Add(this.table35);
			global::Gtk.Notebook.NotebookChild w64 = ((global::Gtk.Notebook.NotebookChild)(this.notebook6[this.table35]));
			w64.Position = 3;
			// Notebook tab
			this.label64 = new global::Gtk.Label();
			this.label64.Name = "label64";
			this.label64.LabelProp = global::Mono.Unix.Catalog.GetString("Dar de baja una Oferta");
			this.notebook6.SetTabLabel(this.table35, this.label64);
			this.label64.ShowAll();
			// Container child notebook6.Gtk.Notebook+NotebookChild
			this.table36 = new global::Gtk.Table(((uint)(4)), ((uint)(3)), false);
			this.table36.Name = "table36";
			this.table36.RowSpacing = ((uint)(6));
			this.table36.ColumnSpacing = ((uint)(6));
			// Container child table36.Gtk.Table+TableChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("Ver Rankeables");
			this.table36.Add(this.button1);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table36[this.button1]));
			w65.LeftAttach = ((uint)(1));
			w65.RightAttach = ((uint)(2));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table36.Gtk.Table+TableChild
			this.CodigoOferta5 = new global::Gtk.Entry();
			this.CodigoOferta5.CanFocus = true;
			this.CodigoOferta5.Name = "CodigoOferta5";
			this.CodigoOferta5.IsEditable = true;
			this.CodigoOferta5.InvisibleChar = '●';
			this.table36.Add(this.CodigoOferta5);
			global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.table36[this.CodigoOferta5]));
			w66.TopAttach = ((uint)(1));
			w66.BottomAttach = ((uint)(2));
			w66.LeftAttach = ((uint)(1));
			w66.RightAttach = ((uint)(2));
			w66.XOptions = ((global::Gtk.AttachOptions)(0));
			w66.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table36.Gtk.Table+TableChild
			this.Estrellas5 = new global::Gtk.Entry();
			this.Estrellas5.CanFocus = true;
			this.Estrellas5.Name = "Estrellas5";
			this.Estrellas5.IsEditable = true;
			this.Estrellas5.InvisibleChar = '●';
			this.table36.Add(this.Estrellas5);
			global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.table36[this.Estrellas5]));
			w67.TopAttach = ((uint)(2));
			w67.BottomAttach = ((uint)(3));
			w67.LeftAttach = ((uint)(1));
			w67.RightAttach = ((uint)(2));
			w67.XOptions = ((global::Gtk.AttachOptions)(0));
			w67.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table36.Gtk.Table+TableChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.textview14 = new global::Gtk.TextView();
			this.textview14.CanFocus = true;
			this.textview14.Name = "textview14";
			this.GtkScrolledWindow3.Add(this.textview14);
			this.table36.Add(this.GtkScrolledWindow3);
			global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.table36[this.GtkScrolledWindow3]));
			w69.TopAttach = ((uint)(3));
			w69.BottomAttach = ((uint)(4));
			w69.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table36.Gtk.Table+TableChild
			this.label183 = new global::Gtk.Label();
			this.label183.Name = "label183";
			this.label183.LabelProp = global::Mono.Unix.Catalog.GetString("Ingrese el código de oferta que desea evaluar");
			this.table36.Add(this.label183);
			global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.table36[this.label183]));
			w70.TopAttach = ((uint)(1));
			w70.BottomAttach = ((uint)(2));
			w70.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table36.Gtk.Table+TableChild
			this.label185 = new global::Gtk.Label();
			this.label185.Name = "label185";
			this.label185.LabelProp = global::Mono.Unix.Catalog.GetString("Un numero entre el 1-5 con el que desea evaluar al contrado");
			this.table36.Add(this.label185);
			global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.table36[this.label185]));
			w71.TopAttach = ((uint)(2));
			w71.BottomAttach = ((uint)(3));
			w71.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table36.Gtk.Table+TableChild
			this.Rankear = new global::Gtk.Button();
			this.Rankear.CanFocus = true;
			this.Rankear.Name = "Rankear";
			this.Rankear.UseUnderline = true;
			this.Rankear.Label = global::Mono.Unix.Catalog.GetString("Ingresar evaluación");
			this.table36.Add(this.Rankear);
			global::Gtk.Table.TableChild w72 = ((global::Gtk.Table.TableChild)(this.table36[this.Rankear]));
			w72.TopAttach = ((uint)(2));
			w72.BottomAttach = ((uint)(3));
			w72.LeftAttach = ((uint)(2));
			w72.RightAttach = ((uint)(3));
			w72.XOptions = ((global::Gtk.AttachOptions)(0));
			w72.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook6.Add(this.table36);
			global::Gtk.Notebook.NotebookChild w73 = ((global::Gtk.Notebook.NotebookChild)(this.notebook6[this.table36]));
			w73.Position = 4;
			// Notebook tab
			this.label65 = new global::Gtk.Label();
			this.label65.Name = "label65";
			this.label65.LabelProp = global::Mono.Unix.Catalog.GetString("Rankear Usuario");
			this.notebook6.SetTabLabel(this.table36, this.label65);
			this.label65.ShowAll();
			// Container child notebook6.Gtk.Notebook+NotebookChild
			this.table37 = new global::Gtk.Table(((uint)(4)), ((uint)(3)), false);
			this.table37.Name = "table37";
			this.table37.RowSpacing = ((uint)(6));
			this.table37.ColumnSpacing = ((uint)(6));
			// Container child table37.Gtk.Table+TableChild
			this.CodigoOferta6 = new global::Gtk.Entry();
			this.CodigoOferta6.CanFocus = true;
			this.CodigoOferta6.Name = "CodigoOferta6";
			this.CodigoOferta6.IsEditable = true;
			this.CodigoOferta6.InvisibleChar = '●';
			this.table37.Add(this.CodigoOferta6);
			global::Gtk.Table.TableChild w74 = ((global::Gtk.Table.TableChild)(this.table37[this.CodigoOferta6]));
			w74.TopAttach = ((uint)(1));
			w74.BottomAttach = ((uint)(2));
			w74.LeftAttach = ((uint)(1));
			w74.RightAttach = ((uint)(2));
			w74.XOptions = ((global::Gtk.AttachOptions)(4));
			w74.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table37.Gtk.Table+TableChild
			this.Comentario6 = new global::Gtk.Entry();
			this.Comentario6.CanFocus = true;
			this.Comentario6.Name = "Comentario6";
			this.Comentario6.IsEditable = true;
			this.Comentario6.InvisibleChar = '●';
			this.table37.Add(this.Comentario6);
			global::Gtk.Table.TableChild w75 = ((global::Gtk.Table.TableChild)(this.table37[this.Comentario6]));
			w75.TopAttach = ((uint)(2));
			w75.BottomAttach = ((uint)(3));
			w75.LeftAttach = ((uint)(1));
			w75.RightAttach = ((uint)(2));
			w75.XOptions = ((global::Gtk.AttachOptions)(4));
			w75.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table37.Gtk.Table+TableChild
			this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
			this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
			this.textview15 = new global::Gtk.TextView();
			this.textview15.CanFocus = true;
			this.textview15.Name = "textview15";
			this.GtkScrolledWindow4.Add(this.textview15);
			this.table37.Add(this.GtkScrolledWindow4);
			global::Gtk.Table.TableChild w77 = ((global::Gtk.Table.TableChild)(this.table37[this.GtkScrolledWindow4]));
			w77.TopAttach = ((uint)(3));
			w77.BottomAttach = ((uint)(4));
			w77.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table37.Gtk.Table+TableChild
			this.IngresarComentario = new global::Gtk.Button();
			this.IngresarComentario.CanFocus = true;
			this.IngresarComentario.Name = "IngresarComentario";
			this.IngresarComentario.UseUnderline = true;
			this.IngresarComentario.Label = global::Mono.Unix.Catalog.GetString("Ingresar Comentario");
			this.table37.Add(this.IngresarComentario);
			global::Gtk.Table.TableChild w78 = ((global::Gtk.Table.TableChild)(this.table37[this.IngresarComentario]));
			w78.TopAttach = ((uint)(2));
			w78.BottomAttach = ((uint)(3));
			w78.LeftAttach = ((uint)(2));
			w78.RightAttach = ((uint)(3));
			w78.XOptions = ((global::Gtk.AttachOptions)(4));
			w78.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table37.Gtk.Table+TableChild
			this.label187 = new global::Gtk.Label();
			this.label187.Name = "label187";
			this.label187.LabelProp = global::Mono.Unix.Catalog.GetString("Código Oferta");
			this.table37.Add(this.label187);
			global::Gtk.Table.TableChild w79 = ((global::Gtk.Table.TableChild)(this.table37[this.label187]));
			w79.TopAttach = ((uint)(1));
			w79.BottomAttach = ((uint)(2));
			w79.XOptions = ((global::Gtk.AttachOptions)(4));
			w79.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table37.Gtk.Table+TableChild
			this.label189 = new global::Gtk.Label();
			this.label189.Name = "label189";
			this.label189.LabelProp = global::Mono.Unix.Catalog.GetString("Comentario");
			this.table37.Add(this.label189);
			global::Gtk.Table.TableChild w80 = ((global::Gtk.Table.TableChild)(this.table37[this.label189]));
			w80.TopAttach = ((uint)(2));
			w80.BottomAttach = ((uint)(3));
			w80.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table37.Gtk.Table+TableChild
			this.VerComentables = new global::Gtk.Button();
			this.VerComentables.CanFocus = true;
			this.VerComentables.Name = "VerComentables";
			this.VerComentables.UseUnderline = true;
			this.VerComentables.Label = global::Mono.Unix.Catalog.GetString("Ver Ofertas comentables");
			this.table37.Add(this.VerComentables);
			global::Gtk.Table.TableChild w81 = ((global::Gtk.Table.TableChild)(this.table37[this.VerComentables]));
			w81.LeftAttach = ((uint)(1));
			w81.RightAttach = ((uint)(2));
			w81.XOptions = ((global::Gtk.AttachOptions)(4));
			w81.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook6.Add(this.table37);
			global::Gtk.Notebook.NotebookChild w82 = ((global::Gtk.Notebook.NotebookChild)(this.notebook6[this.table37]));
			w82.Position = 5;
			// Notebook tab
			this.label182 = new global::Gtk.Label();
			this.label182.Name = "label182";
			this.label182.LabelProp = global::Mono.Unix.Catalog.GetString("Ingresar comentario Usuario");
			this.notebook6.SetTabLabel(this.table37, this.label182);
			this.label182.ShowAll();
			// Container child notebook6.Gtk.Notebook+NotebookChild
			this.table2 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.GtkScrolledWindow5 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow5.Name = "GtkScrolledWindow5";
			this.GtkScrolledWindow5.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow5.Gtk.Container+ContainerChild
			this.textview16 = new global::Gtk.TextView();
			this.textview16.CanFocus = true;
			this.textview16.Name = "textview16";
			this.GtkScrolledWindow5.Add(this.textview16);
			this.table2.Add(this.GtkScrolledWindow5);
			global::Gtk.Table.TableChild w84 = ((global::Gtk.Table.TableChild)(this.table2[this.GtkScrolledWindow5]));
			w84.LeftAttach = ((uint)(1));
			w84.RightAttach = ((uint)(2));
			w84.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.GtkScrolledWindow6 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow6.Name = "GtkScrolledWindow6";
			this.GtkScrolledWindow6.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow6.Gtk.Container+ContainerChild
			this.textview18 = new global::Gtk.TextView();
			this.textview18.CanFocus = true;
			this.textview18.Name = "textview18";
			this.GtkScrolledWindow6.Add(this.textview18);
			this.table2.Add(this.GtkScrolledWindow6);
			global::Gtk.Table.TableChild w86 = ((global::Gtk.Table.TableChild)(this.table2[this.GtkScrolledWindow6]));
			w86.TopAttach = ((uint)(1));
			w86.BottomAttach = ((uint)(2));
			w86.LeftAttach = ((uint)(1));
			w86.RightAttach = ((uint)(2));
			w86.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.VerMisOfertas = new global::Gtk.Button();
			this.VerMisOfertas.CanFocus = true;
			this.VerMisOfertas.Name = "VerMisOfertas";
			this.VerMisOfertas.UseUnderline = true;
			this.VerMisOfertas.Label = global::Mono.Unix.Catalog.GetString("Ver mis Ofertas");
			this.table2.Add(this.VerMisOfertas);
			global::Gtk.Table.TableChild w87 = ((global::Gtk.Table.TableChild)(this.table2[this.VerMisOfertas]));
			w87.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.VerOfertasAceptadas = new global::Gtk.Button();
			this.VerOfertasAceptadas.CanFocus = true;
			this.VerOfertasAceptadas.Name = "VerOfertasAceptadas";
			this.VerOfertasAceptadas.UseUnderline = true;
			this.VerOfertasAceptadas.Label = global::Mono.Unix.Catalog.GetString("Ver Ofertas aceptadas");
			this.table2.Add(this.VerOfertasAceptadas);
			global::Gtk.Table.TableChild w88 = ((global::Gtk.Table.TableChild)(this.table2[this.VerOfertasAceptadas]));
			w88.TopAttach = ((uint)(1));
			w88.BottomAttach = ((uint)(2));
			w88.XOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook6.Add(this.table2);
			global::Gtk.Notebook.NotebookChild w89 = ((global::Gtk.Notebook.NotebookChild)(this.notebook6[this.table2]));
			w89.Position = 6;
			// Notebook tab
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Mis Ofertas");
			this.notebook6.SetTabLabel(this.table2, this.label1);
			this.label1.ShowAll();
			// Container child notebook6.Gtk.Notebook+NotebookChild
			this.table38 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table38.Name = "table38";
			this.table38.RowSpacing = ((uint)(6));
			this.table38.ColumnSpacing = ((uint)(6));
			// Container child table38.Gtk.Table+TableChild
			this.ApagarPrograma = new global::Gtk.Button();
			this.ApagarPrograma.CanFocus = true;
			this.ApagarPrograma.Name = "ApagarPrograma";
			this.ApagarPrograma.UseUnderline = true;
			this.ApagarPrograma.Label = global::Mono.Unix.Catalog.GetString("Apagar Programa");
			this.table38.Add(this.ApagarPrograma);
			global::Gtk.Table.TableChild w90 = ((global::Gtk.Table.TableChild)(this.table38[this.ApagarPrograma]));
			w90.TopAttach = ((uint)(1));
			w90.BottomAttach = ((uint)(2));
			w90.LeftAttach = ((uint)(2));
			w90.RightAttach = ((uint)(3));
			w90.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table38.Gtk.Table+TableChild
			this.CerrarSesion = new global::Gtk.Button();
			this.CerrarSesion.CanFocus = true;
			this.CerrarSesion.Name = "CerrarSesion";
			this.CerrarSesion.UseUnderline = true;
			this.CerrarSesion.Label = global::Mono.Unix.Catalog.GetString("Cerrar Sesión");
			this.table38.Add(this.CerrarSesion);
			global::Gtk.Table.TableChild w91 = ((global::Gtk.Table.TableChild)(this.table38[this.CerrarSesion]));
			w91.TopAttach = ((uint)(1));
			w91.BottomAttach = ((uint)(2));
			w91.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook6.Add(this.table38);
			global::Gtk.Notebook.NotebookChild w92 = ((global::Gtk.Notebook.NotebookChild)(this.notebook6[this.table38]));
			w92.Position = 7;
			// Notebook tab
			this.label66 = new global::Gtk.Label();
			this.label66.Name = "label66";
			this.label66.LabelProp = global::Mono.Unix.Catalog.GetString("Cerrar Sesión");
			this.notebook6.SetTabLabel(this.table38, this.label66);
			this.label66.ShowAll();
			this.Add(this.notebook6);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 974;
			this.DefaultHeight = 484;
			this.Show();
			this.Investigacion1.Toggled += new global::System.EventHandler(this.OnInvestigacion1Toggled);
			this.IngresarOferta.Clicked += new global::System.EventHandler(this.OnIngresarOfertaClicked);
			this.VerOfertas.Clicked += new global::System.EventHandler(this.OnVerOfertasClicked);
			this.button40.Clicked += new global::System.EventHandler(this.OnButton40Clicked);
			this.VerPostulantes.Clicked += new global::System.EventHandler(this.OnVerPostulantesClicked);
			this.VerOfertas3.Clicked += new global::System.EventHandler(this.OnVerOfertas3Clicked);
			this.AceptarPostulante.Clicked += new global::System.EventHandler(this.OnAceptarPostulanteClicked);
			this.VerBajables.Clicked += new global::System.EventHandler(this.OnVerBajablesClicked);
			this.DarDeBaja.Clicked += new global::System.EventHandler(this.OnDarDeBajaClicked);
			this.Rankear.Clicked += new global::System.EventHandler(this.OnRankearClicked);
			this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
			this.VerComentables.Clicked += new global::System.EventHandler(this.OnVerComentablesClicked);
			this.IngresarComentario.Clicked += new global::System.EventHandler(this.OnIngresarComentarioClicked);
			this.VerOfertasAceptadas.Clicked += new global::System.EventHandler(this.OnVerOfertasAceptadasClicked);
			this.VerMisOfertas.Clicked += new global::System.EventHandler(this.OnButton2Clicked);
			this.CerrarSesion.Clicked += new global::System.EventHandler(this.OnCerrarSesionClicked);
			this.ApagarPrograma.Clicked += new global::System.EventHandler(this.OnApagarProgramaClicked);
		}
	}
}
