
// This file has been generated by the GUI designer. Do not modify.
namespace gtk
{
	public partial class FourthWindow
	{
		private global::Gtk.VBox vbox54;

		private global::Gtk.Table table1;

		private global::Gtk.Button CerrarPrograma;

		private global::Gtk.Label label59;

		private global::Gtk.Entry Rut;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Button Registrarme;

		private global::Gtk.Button IniciarSesion;

		private global::Gtk.HBox hbox11;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget gtk.FourthWindow
			this.Name = "gtk.FourthWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("FourthWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child gtk.FourthWindow.Gtk.Container+ContainerChild
			this.vbox54 = new global::Gtk.VBox();
			this.vbox54.Name = "vbox54";
			this.vbox54.Spacing = 6;
			// Container child vbox54.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.CerrarPrograma = new global::Gtk.Button();
			this.CerrarPrograma.CanFocus = true;
			this.CerrarPrograma.Name = "CerrarPrograma";
			this.CerrarPrograma.UseUnderline = true;
			this.CerrarPrograma.Label = global::Mono.Unix.Catalog.GetString("Cerrar Programa");
			this.table1.Add(this.CerrarPrograma);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.CerrarPrograma]));
			w1.XOptions = ((global::Gtk.AttachOptions)(0));
			w1.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table1.Gtk.Table+TableChild
			this.label59 = new global::Gtk.Label();
			this.label59.Name = "label59";
			this.label59.LabelProp = global::Mono.Unix.Catalog.GetString("Rut/Credencial");
			this.table1.Add(this.label59);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.label59]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.Rut = new global::Gtk.Entry();
			this.Rut.CanFocus = true;
			this.Rut.Name = "Rut";
			this.Rut.IsEditable = true;
			this.Rut.InvisibleChar = '●';
			this.table1.Add(this.Rut);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.Rut]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox54.Add(this.table1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox54[this.table1]));
			w4.Position = 0;
			// Container child vbox54.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.Registrarme = new global::Gtk.Button();
			this.Registrarme.CanFocus = true;
			this.Registrarme.Name = "Registrarme";
			this.Registrarme.UseUnderline = true;
			this.Registrarme.Label = global::Mono.Unix.Catalog.GetString("Volver");
			this.hbox9.Add(this.Registrarme);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.Registrarme]));
			w5.Position = 0;
			w5.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.IniciarSesion = new global::Gtk.Button();
			this.IniciarSesion.CanFocus = true;
			this.IniciarSesion.Name = "IniciarSesion";
			this.IniciarSesion.UseUnderline = true;
			this.IniciarSesion.Label = global::Mono.Unix.Catalog.GetString("Iniciar Sesión");
			this.hbox9.Add(this.IniciarSesion);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.IniciarSesion]));
			w6.Position = 1;
			w6.Fill = false;
			this.vbox54.Add(this.hbox9);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox54[this.hbox9]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox54.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			this.vbox54.Add(this.hbox11);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox54[this.hbox11]));
			w8.Position = 2;
			this.Add(this.vbox54);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.CerrarPrograma.Clicked += new global::System.EventHandler(this.OnCerrarProgramaClicked);
			this.Registrarme.Clicked += new global::System.EventHandler(this.OnVolverClicked);
			this.IniciarSesion.Clicked += new global::System.EventHandler(this.OnIniciarSesionClicked);
		}
	}
}
