
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed3;

	private global::Gtk.Fixed fixed4;

	private global::Gtk.Label label4;

	private global::Gtk.Button Enter;

	private global::Gtk.Button CerrarPrograma;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed3 = new global::Gtk.Fixed();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.fixed4 = new global::Gtk.Fixed();
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		this.fixed3.Add(this.fixed4);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.fixed4]));
		w1.X = 321;
		w1.Y = 211;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Bienvenidos a Ofertas Laborales");
		this.fixed3.Add(this.label4);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.label4]));
		w2.X = 195;
		w2.Y = 163;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.Enter = new global::Gtk.Button();
		this.Enter.CanFocus = true;
		this.Enter.Name = "Enter";
		this.Enter.UseUnderline = true;
		this.Enter.Label = global::Mono.Unix.Catalog.GetString("Ingresar");
		this.fixed3.Add(this.Enter);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.Enter]));
		w3.X = 258;
		w3.Y = 260;
		// Container child fixed3.Gtk.Fixed+FixedChild
		this.CerrarPrograma = new global::Gtk.Button();
		this.CerrarPrograma.CanFocus = true;
		this.CerrarPrograma.Name = "CerrarPrograma";
		this.CerrarPrograma.UseUnderline = true;
		this.CerrarPrograma.Label = global::Mono.Unix.Catalog.GetString("Cerrar Programa");
		this.fixed3.Add(this.CerrarPrograma);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.CerrarPrograma]));
		w4.X = 16;
		w4.Y = 12;
		this.Add(this.fixed3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 617;
		this.DefaultHeight = 459;
		this.Show();
		this.Enter.Clicked += new global::System.EventHandler(this.OnEnterClicked);
		this.CerrarPrograma.Clicked += new global::System.EventHandler(this.OnCerrarProgramaClicked);
	}
}
